server:
  port: 8080
spring:
  application:
    name: spring-boot-mybaits
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://peer1:3306/mybatis-demo?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//peer3:1521/helowinXDB
    username: test
    password: test

mybatis-plus:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
