spring:
  redis:
    host: peer1
    port: 6379
#    password: 123456
    database: 0   # redis数据库编号，默认为0
    timeout: 60s  # 连接超时时间
    jedis:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1s   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8     # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
        time-between-eviction-runs: 60s    # 空闲链接检测线程检测周期。如果为负值，表示不运行检测线程。



