spring:
  application:
    name: springboot-dubbo-provider-B
server:
  port: 9090
dubbo:
  application:
    name: springboot-dubbo-provider-B
  registry:
    protocol: zookeeper
    address: zookeeper://peer1:2181
  protocol:
    name: dubbo
    port: 20880



