server:
  port: 8080
spring:
  application:
    name: spring-boot-shardingsphere
  shardingsphere:
    datasource:
      # 数据源名称，不能留有空格
      name: master0,master1,master2,slave0,slave1,slave2
      master0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://peer1:3306/sharding_sphere_demo_0?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      slave0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://peer1:3307/sharding_sphere_demo_0?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      master1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://peer1:3306/sharding_sphere_demo_1?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      slave1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://peer1:3307/sharding_sphere_demo_1?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      master2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://peer1:3306/sharding_sphere_demo_2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      slave2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://peer1:3307/sharding_sphere_demo_2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
    masterslave:
      name: ms
      master-data-source-names: master0,master1,master2
      slave-data-source-names: slave0,slave1,slave2
    props:
      sql:
        show: true
    sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: sharding_sphere_demo_$->{id % 3}
      tables:
        user:
          actual-data-nodes: sharding_sphere_demo_$->{0..2}.user_$->{0..3}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id % 4}
        order:
          actual-data-nodes: sharding_sphere_demo_$->{0..2}.order_$->{0..3}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: order_$->{user_id % 4}
      master-slave-rules:
        ds0:
          master-data-source-name: master0
          slave-data-source-names: slave0
        ds1:
          master-data-source-name: master1
          slave-data-source-names: slave1
        ds2:
          master-data-source-name: master2
          slave-data-source-names: slave2
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml