server:
  port: 8080
spring:
  application:
    name: springboot-activemq
  activemq:
    broker-url: tcp://peer1:61616
    user: holmes
    password: 123456
    in-memory: false
    send-timeout: 3s
    pool:
      # 是否使用连接池
      enabled: true
      # 连接池最大连接数
      max-connections: 10
      # 空闲连接过期时间
      idle-timeout: 30s